version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    image: node:12
    working_dir: /usr/src/cleanSurvey/
    restart: always
    command: bash -c "npm install --only=production && npm run debug"
    volumes:
      - ./dist/:/usr/src/cleanSurvey/dist
      - ./package.json:/usr/src/cleanSurvey/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo